- name: Ensure a directory exist for the quicklisp sources
  file:
    path: "{{ working_directory }}"
    state: directory
- name: Download Quicklisp
  get_url:
    url: "{{ ql_url }}"
    dest: "{{ working_directory }}"
- name: QuickLisp setup
  block:
    - name: "Update quicklisp in {{ user_name }} user space"
      command:
      args:
        chdir: "{{ user_home }}/"
        cmd: "sbcl --disable-debugger --eval \"(progn (ql:update-client) (exit))\""
        removes: "{{ user_home }}/quicklisp"
      # become: True
      # become_user: "{{ user_name }}"
    - name: "Install quicklisp client for user {{ user_name }}"
      command:
      args:
        chdir: "{{ user_home }}/"
        cmd: "sbcl --disable-debugger --load {{ working_directory }}/quicklisp.lisp --eval \"(progn (quicklisp-quickstart:install) (exit))\""
        creates: "{{ user_home }}/quicklisp"
      register: ql_res
      # become: True
      # become_user: "{{ user_name }}"
    - debug:
        msg: "Content of ql_res: {{ ql_res }}"
    - name: "Initialize Quicklisp in {{ user_name }} user space"
      block:
        # It is necessary to patch this file, else, the command in the
        # next task will ask for pressing enter (Ansible doesn't
        # manage interactive applications, AFAIK).
        - name: Patch quicklisp/quicklisp/impl-util.lisp
          lineinfile:
            line: "(when (eq 1 1)"
            regexp: "\\(ql-util:press-enter-to-continue\\)"
            path: "{{ user_home }}/quicklisp/quicklisp/impl-util.lisp"
            state: present
        - name: Ensure quicklisp is automatically loaded
          command: "sbcl --disable-debugger --load {{ user_home }}/quicklisp/setup.lisp --eval \"(progn (ql:add-to-init-file) (exit))\""
          args:
            chdir: "{{ user_home }}"
    - name: "Update common lisp packages in {{ user_name }} user space"
      command: 'sbcl --disable-debugger --eval "(progn (ql:update-dist \"quicklisp\") (exit))"'
      args:
        chdir: "{{ user_home }}"
  become: True
  become_user: "{{ user_name }}"
